### ISSUE TITLE
should `dummy-files` be renamed to `templates`?

### ISSUE THREAD

**Issue by baileyb0t** [HRDAG/training-docs#4]

**Comment by baileyb0t** [comment]
Additionally, should templates be created for:
- bash scripts
- Julia scripts

**Comment by mep7** [comment]
Sure, I like templates as a name for these files. And I think yes to a `~/.bashrc` template. I'm not familiar enough with Julia to have an opinion on that one...does it make sense to have a Julia template or more just some examples? (is there a useful distinction to be made between template and example?)

**Comment by baileyb0t** [comment]
Okay, I'll rename `dummy-files` to `templates`.

In terms of distinction, I think of a template as something that has the barebones but needs filling in, where an example should standalone in practice. These files won't compile unless their contents are changed to match some repo, so I think template makes sense here, but that may just be my interpretation!

I suggested Julia to round out some of the languages I've seen used in projects, and to get another example in the makefile of compiling a target from a script, but I think it would be fair to just have some examples of Julia code or scripts instead of pushing a template.
